server {
    listen 80;
    listen [::]:80;
    server_name {{DOMAIN}};

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {{DOMAIN}};

    ssl_certificate /etc/blackout/ssl/fullchain.pem;
    ssl_certificate_key /etc/blackout/ssl/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    location = {{WS_PATH}} {
        proxy_http_version 1.1;
        proxy_set_header Host {{DOMAIN}};
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://unix:/dev/shm/blackout-vless.sock:{{WS_PATH}};
    }

    location /blackout-api/ {
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://127.0.0.1:8787;
    }
}
